name: Node.js CI

on:
  push:
  pull_request:
    branches: [main]

env:
  # DEBUG: '@node-loaders:*'
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install -g npm@^8
        if: matrix.node-version == '14.x'
      - run: npm ci
      - run: npm test
        if: matrix.node-version != '14.x' && (matrix.node-version != '16.x' || matrix.os != 'ubuntu-latest')
      - run: npm run test-node14
        # Mock tests fails due to conflict with esbuild loader, should use auto instead
        if: matrix.node-version == '14.x'
      - run: npm run test-coverage
        if: matrix.node-version == '16.x' && matrix.os == 'ubuntu-latest'
